name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -r git@github.com:haliphax/nubbins.git

  package:
    needs: release
    uses: ./.github/workflows/package.yml
