name: Publish site

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish site
        run: |
          #--- build site
          npm run build
          mkdir docs
          cp index.html dist/nubbins.min.css docs/
          sed -i -e "s/src\/index/nubbins.min/" docs/index.html

          #--- publish to GitHub Pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f docs
          git commit -m "🚀 publish site"
          git push -f -u origin main:gh-pages
